### ISSUE TITLE
rrd graph error on new deployment

### ISSUE THREAD

**Issue by wayneeseguin** [cloudfoundry-community/bolo-boshrelease#18]
Error message:
  `ERROR: width below 10 pixels`

Steps I did to get this error: 
1. deployed new bolo-boshrelease via Genesis template to an aws account
2. visited the web UI
3. observed the graphs were all partially rendered

Log details here: https://gist.github.com/wayneeseguin/3ce081134f0fe27e1bf212ad0ebf3857

I also tried tweaking the URI parameters to the defaults for rrd graphs, no luck.

**Comment by geofffranks** [comment]
This is fixed as of v0.2.4 of bolo-release. The problem was in [Gnossis's error handling for graph rendering](https://github.com/bolo/gnossis/commit/ec603daee63090da333f46f45429c1ebb9e48490), (fixed in [v0.6 of Gnossis](https://github.com/bolo/gnossis/releases/tag/v0.6)).

In addition, I think you were running into these errors because rrdcached was not properly enabled in the Genesis templates for bolo, until [this commit](https://github.com/starkandwayne/bolo-deployment/commit/3c9600aa77ac175077763c3e63348919e96dbbcb).

**Comment by jhunt** [comment]
Thanks @geofffranks !
